### PR TITLE
add sim76xx device support

### PR DESCRIPTION
**Pull request by thomasonegd**
add sim76xx serial devices support.has been tested on sim7600ce.

### CODE REVIEW

**Comment by Lawlieta** [comment]
你好，感谢你的代码贡献，代码合并之前需要先通过功能测试，请你先验证确保如下软件包和网络功能测试正常。
- at_ping/at_ifconfig 功能（自定义添加功能）
- wenclient 软件包（使用软件包自带示例测试）
- mqtt 软件包
- mbedtls 软件包
- onenet 软件包
- NTP 功能（netutils 软件包）
- ipref 功能（netutils 软件包）

**Comment by thomasonegd** [comment]
at_ping & at_ifconfig has been tested

**Comment by Lawlieta** [comment]
Have you tested other network software packages，like webclient package?

**Comment by thomasonegd** [comment]
Not yet util now,but i can test some network pkgs like NTP & ipref.should I must test all of the pkgs you list out?

**Comment by armink** [comment]
这些个网络软件包使用的网络技术各不相同，所以当时有定这样一个测试方案，这里面有详细的说明，
https://www.rt-thread.org/qa/thread-7660-1-1.html

辛苦下了哈~

**Comment by Lawlieta** [comment]
We hope to get a stable software package for later use and maintenance, so it is recommended to complete the test of these network functions, thanks.

**Comment by Lawlieta** [comment]
ping @thomasonegd

**Comment by thomasonegd** [comment]
under perf test now

**Comment by thomasonegd** [comment]
I have tested all the above items。
iperf for 22hours, not found any problems

at_ping/ap_ifconfig & webclient & mbedtls & ntp also pass the test.

**but there seems something wrong with onenet&mqtt. the device can connect to the onenet cloud,but it will offline sometime ,and will reconnect to the cloud.**

**Comment by thomasonegd** [comment]
Fixed the bug that sometimes the modem went offline.the problem is under the driver layer

**Comment by thomasonegd** [comment]
all of the items have pass the test.

**Comment by armink** [comment]
👍 非常感谢你的贡献，RT-Thread 的 at device 支持有成长了一步

**Pull request merged**
